# Generated by Django 4.2.11 on 2024-05-26 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_attendance_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='deadline',
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='attendance',
            name='first_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='attendance',
            name='last_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
