# Generated by Django 4.2.11 on 2024-06-02 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_created_at_event_timezone'),
        ('events', '0004_remove_event_deadline_attendance_employee_id_and_more'),
    ]

    operations = [
    ]
