# Generated by Django 4.2.11 on 2024-05-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_attendance_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_public',
        ),
        migrations.AddField(
            model_name='event',
            name='access',
            field=models.TextField(choices=[('Public', 'public'), ('On Invite', 'on_invite'), ('Restricted', 'restricted')], default='public', max_length=20),
        ),
    ]
