# Generated by Django 4.2.11 on 2024-06-01 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_merge_20240530_2236'),
        ('events', '0007_remove_event_is_public_event_access'),
    ]

    operations = [
    ]
