# Generated by Django 4.2.11 on 2024-06-04 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_satsuserprofile'),
        ('events', '0010_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(default='')),
                ('last_name', models.TextField(default='')),
                ('employee_id', models.TextField(default='')),
                ('is_activated', models.BooleanField(default=False)),
                ('clock_in_time', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('eventSession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventsession')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.satsuser', to_field='magic_string')),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
