# Generated by Django 4.2.11 on 2024-06-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_delete_attendancebackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
