# Generated by Django 4.2.11 on 2024-06-04 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_attendancebackup'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancebackup',
            unique_together=set(),
        ),
    ]
