# Generated by Django 4.2.11 on 2024-06-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_attendance_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsession',
            name='deadline_string',
            field=models.CharField(null=True),
        ),
    ]
