# Generated by Django 4.2.11 on 2024-06-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_eventsession_deadline_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsession',
            name='deadline_string',
            field=models.CharField(blank=True, null=True),
        ),
    ]
