# Generated by Django 4.2.11 on 2024-05-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_fcmtoken_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatsUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magic_string', models.TextField(unique=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
            ],
        ),
    ]
