# Generated by Django 4.2.11 on 2024-06-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_satsuserprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SatsUserProfile',
        ),
    ]
