# Generated by Django 4.2.11 on 2024-06-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_satsuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='satsuser',
            name='first_name',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='satsuser',
            name='last_name',
            field=models.TextField(default='', null=True),
        ),
    ]
