# Generated by Django 4.2.11 on 2024-06-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_satsuser_first_name_satsuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='satsuser',
            name='sats_balance',
            field=models.IntegerField(default=0),
        ),
    ]
