# Generated by Django 4.2.11 on 2024-06-05 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0009_satsuser_first_name_satsuser_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry', models.BigIntegerField()),
                ('min_withdrawable', models.IntegerField()),
                ('max_withdrawable', models.IntegerField()),
                ('amount_withdrawn', models.IntegerField(null=True)),
                ('funds_claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.satsuser')),
            ],
        ),
    ]
