# Generated by Django 4.2.11 on 2024-06-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_satsuser_first_name_satsuser_last_name'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WithdrawalRequests',
            new_name='WithdrawalRequest',
        ),
    ]
